# Generated by Django 5.2 on 2025-05-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_rename_type_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='changedate',
        ),
        migrations.AddField(
            model_name='date',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.transaction'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
