# Generated by Django 5.2 on 2025-05-03 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_remove_date_changedate_date_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.type'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.transaction'),
        ),
    ]
